---
name: XHTML-MediaWiki
version: 0.02
author:
  - '"G. Allen Morris III" <gam3@gam3.net>'
abstract: Convert MediaWiki text to xhtml
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Parser: 0
  Params::Validate: 0.85
  perl: 5.6.0
build_requires:
  Test::XML: 0
  Test::XML::Order: 0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::XML: 0
provides:
  XHTML::MediaWiki:
    file: lib/XHTML/MediaWiki.pm
    version: 0.02
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
